/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.aridair;



import java.sql.Connection;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author awant
 */
public final class serchcustomer extends javax.swing.JInternalFrame {

    private java.util.Date date;

    /**
     * Creates new form Addcustomer
     */
    public serchcustomer() {
        initComponents();
        this.autoid();
    }
    Connection con;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void autoid(){ 
        try {
           Class.forName("com.mysql.jdbc.driver");
         con =DriverManager.getConnection("jdbc:mysql://localhost/aridair","tayyab","1223334444");
              con=DatabaseManager.getConnected();
           ResultSet ra = s.executeQuery("select MAX(id from customer");
           ra.next();
           ra.getString("MAX(id)");
           if(ra.getString("MAX(id)")==null){
                 customerid.setText("7001");
            }
           else
           {
               long id = Long.parseLong(ra.getString("MAX(id)").substring(2,ra.getString("MAX(id").length()));
               id++;
               customerid.setText("AridAir"+String.format("%04d",id ));
           }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(serchcustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(serchcustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        arrayListModel1 = new com.jgoodies.common.collect.ArrayListModel();
        arrayListModel2 = new com.jgoodies.common.collect.ArrayListModel();
        ignoredBuilder1 = new org.junit.internal.builders.IgnoredBuilder();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        passportid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        caddress = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        cnic = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        contect = new javax.swing.JTextField();
        doob = new com.toedter.calendar.JDateChooser();
        bcuttomerexit = new javax.swing.JButton();
        bcutomeradd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        customerid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setPreferredSize(new java.awt.Dimension(850, 425));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Passport id");

        jLabel4.setText("Address");

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(caddress);

        jLabel11.setText("CNIC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lastname)
                    .addComponent(firstname)
                    .addComponent(passportid)
                    .addComponent(cnic))
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passportid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(47, 47, 47))))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setText("DOB");

        jLabel6.setText("Gender");

        r1.setText("Male");

        r2.setText("Female");

        jLabel7.setText("Contect");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(r1)
                        .addGap(18, 18, 18)
                        .addComponent(r2))
                    .addComponent(contect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(doob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(r1)
                    .addComponent(r2))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(contect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        bcuttomerexit.setText("Exit");
        bcuttomerexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcuttomerexitActionPerformed(evt);
            }
        });

        bcutomeradd.setText("Update");
        bcutomeradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcutomeraddActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Customer Id");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(customerid, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(bcuttomerexit)
                        .addGap(84, 84, 84)
                        .addComponent(bcutomeradd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(customerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bcuttomerexit)
                            .addComponent(bcutomeradd)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcutomeraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcutomeraddActionPerformed
        // TODO add your handling code here:
          
        String id= jLabel9.getText();
        String fn= firstname.getText();
        String ls= lastname.getText();
        
        String passid= passportid.getText();
        String nic= cnic.getText();
        String addr= caddress.getText();
        DateFormat da =new SimpleDateFormat("yyyy-MM-dd");
        String date = da.format(doob.getDate());
        String gender;
        if(r1.isSelected()){
            gender="Male";
        }else
        {
            gender="Female";
        }
       String cont= contect.getText();
       
       
            try {
                Class.forName("com.mysql.jdbc.driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/aridair","tayyab","1223334444");
                pst = con.prepareStatement("update  customer set,First_Name=?,Last_Name=?,Passpord_id=?,CNIC=?,Address=?,DOB=?,Gender=?,Contect=?,jLabel9=?");
                //pst.setString(1,id);
                pst.setString(1,fn);
                pst.setString(2,ls);
                pst.setString(3,passid);
                pst.setString(4,nic);
                pst.setString(5,addr);
                pst.setString(6,date);
                pst.setString(7,gender);
                pst.setString(8,cont);
                pst.setString(9,id);
                
                pst.executeUpdate();
                
               JOptionPane.showMessageDialog(null,"Registration Update (***)");
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(serchcustomer.class.getName()).log(Level.SEVERE, null, ex);
            }catch (SQLException ex) {
            Logger.getLogger(serchcustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
           
       
           
    }//GEN-LAST:event_bcutomeraddActionPerformed

    private void bcuttomerexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcuttomerexitActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_bcuttomerexitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String id = customerid.getText();
        
        try {
    // TODO add your handling code here
   

    Class.forName("com.mysql.jdbc.Driver"); // Note the correct class name
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aridair", "tayyab", "1223334444");
    PreparedStatement pst = con.prepareStatement("SELECT * FROM customer WHERE id=?"); // Corrected the SQL query
    pst.setString(1, id);
    ResultSet ra = pst.executeQuery(); // Corrected the variable name

    // Process the ResultSet as needed

    // Close resources (Connection, PreparedStatement, and ResultSet) when done
    if (!ra.next()) { // Use !ra.next() to check if no records were found
        JOptionPane.showMessageDialog(this, "Record not Found");
    } else {
        String fn = ra.getString("First_name");
        String ls = ra.getString("Last_name");
        String nic = ra.getString("CNIC");
        String passid = ra.getString("passport_id");
        String addr = ra.getString("Address");
        String dob = ra.getString("DOB");

        // Parsing the date string into a Date object
        try {
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dob);
            // Now, 'date' contains the parsed Date object
            System.out.println("Parsed Date: " + date);
        } catch (ParseException e) {
            e.printStackTrace();
            // Handle the exception, e.g., log it or provide a default date
        }

        String gender = ra.getString("Gender");

        if (gender.equals("Female")) {
            r1.setSelected(false);
            r2.setSelected(true);
        } else {
            r1.setSelected(true);
            r2.setSelected(false);
        }

        String cont = ra.getString("Contect");

        firstname.setText(fn.trim());
        lastname.setText(ls.trim());
        cnic.setText(nic.trim());
        passportid.setText(passid.trim());
        caddress.setText(addr.trim());
        contect.setText(cont.trim()); // Corrected variable name
        doob.setDate(date);
    }

} catch (SQLException ex) {
    Logger.getLogger(serchcustomer.class.getName()).log(Level.SEVERE, null, ex);
} catch (ClassNotFoundException ex) {
    Logger.getLogger(serchcustomer.class.getName()).log(Level.SEVERE, null, ex);
} finally {
    // Close resources in a finally block to ensure they are always closed
    try {
        if (con != null) {
            con.close();
        }
        if (pst != null) {
            pst.close();
        }
        Object ra = null;
        if (ra != null) {
            
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

            
            
                
     

    }//GEN-LAST:event_jButton1ActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jgoodies.common.collect.ArrayListModel arrayListModel1;
    private com.jgoodies.common.collect.ArrayListModel arrayListModel2;
    private javax.swing.JButton bcutomeradd;
    private javax.swing.JButton bcuttomerexit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextPane caddress;
    private javax.swing.JTextField cnic;
    private javax.swing.JTextField contect;
    private javax.swing.JTextField customerid;
    private com.toedter.calendar.JDateChooser doob;
    private javax.swing.JTextField firstname;
    private org.junit.internal.builders.IgnoredBuilder ignoredBuilder1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField passportid;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    // End of variables declaration//GEN-END:variables

}


      

